apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  type: NodePort
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 80         # Port inside the cluster
      targetPort: 8501 # Streamlit port
      nodePort: 30001  # Port you will use in your browser
